version: '3.8'

services:
  hadoop-namenode:
    image: bde2020/hadoop-namenode:latest
    container_name: hadoop-namenode
    environment:
      - CLUSTER_NAME=hadoop-cluster
      - CORE_CONF_fs_defaultFS=hdfs://hadoop-namenode:9000
      - HDFS_NAMENODE_RPC_PORT_NUMBER=9000
      - HDFS_NAMENODE_HTTP_PORT_NUMBER=9870
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - hadoop_namenode:/hadoop/dfs/name

  hadoop-datanode:
    image: bde2020/hadoop-datanode:latest
    container_name: hadoop-datanode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://hadoop-namenode:9000
      - HDFS_DATANODE_ADDRESS=0.0.0.0:9866
      - HDFS_DATANODE_HTTP_ADDRESS=0.0.0.0:9864
      - HDFS_NAMENODE_HOSTNAME=hadoop-namenode
      - ALLOW_EMPTY_PASSWORD=yes
    depends_on:
      - hadoop-namenode
    volumes:
      - hadoop_datanode:/hadoop/dfs/data

  spark-master:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"
      - "7077:7077"
    depends_on:
      - hadoop-namenode

  spark-worker:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master

  jupyter:
    build: .
    ports:
      - "8888:8888"
      - "4040-4050:4040-4050"
    volumes:
      - ./notebooks:/workspace
      - ./data:/data
    depends_on:
      - spark-master
      - hadoop-namenode

volumes:
  hadoop_namenode:
  hadoop_datanode:
